version = 0.1
[prod]
[prod.deploy]
[prod.deploy.parameters]
parameter_overrides=[
  "NodeENV=production",
  "HarvardArtMuseumsApi=https://api.harvardartmuseums.org",
  "WildcardDomainCertArn=https://api.harvardartmuseums.org",
  "WildcardDomainCertArn=arn:aws:acm:us-east-1:353196159109:certificate/b7e23fbf-69a3-440f-8560-59f240f2cc09",
  "BaseDomainName=rdok.co.uk",
  "DomainHostedZoneID=ZSY7GT2NEDPN0",
  "CorsOriginsCommaDelimited=https://studio.apollographql.com",
]

[test]
[test.deploy]
[test.deploy.parameters]
parameter_overrides=[
  "NodeENV=test",
  "HarvardArtMuseumsApi=https://api.harvardartmuseums.org",
  "WildcardDomainCertArn=arn:aws:acm:us-east-1:353196159109:certificate/b7e23fbf-69a3-440f-8560-59f240f2cc09",
  "BaseDomainName=rdok.co.uk",
  "DomainHostedZoneID=ZSY7GT2NEDPN0",
  "CorsOriginsCommaDelimited=https://studio.apollographql.com",
]

[dev]
[dev.deploy]
[dev.deploy.parameters]
parameter_overrides=[
  "NodeENV=dev",
  "HarvardArtMuseumsApi=https://api.harvardartmuseums.org",
  "WildcardDomainCertArn=arn:aws:acm:us-east-1:353196159109:certificate/b7e23fbf-69a3-440f-8560-59f240f2cc09",
  "BaseDomainName=rdok.co.uk",
  "DomainHostedZoneID=ZSY7GT2NEDPN0",
  "CorsOriginsCommaDelimited=https://studio.apollographql.com",
]
